export const teammates = [
	{
		_category: 'teammates',
		_id: 'mate1',
		firstName: 'Григорий',
		lastName: 'Герасимов',
		age: '33',
		team: 'Hackathon Team 5',
		position: 'Team Lead',
		role: 'teamlead',
		intro: 'Начинающий ReactJS фронт-энд разработчик',
		imgPath: 'https://i.kinja-img.com/gawker-media/image/upload/jx5u6rwdhx0fzxty1mhn.jpg',
		hobbies: ['#webtech', '#webdes', '#mus', '#vid', '#cul', '#cyc', 'hik'],
		technologies: {
			html: '55',
			css: '40',
			js: '50',
			react: '60',
		},
		tasks: [
			'архитектура проекта',
			'структура папок и компонентов',
			'разработка главной страницы',
			'разработка концепции общей страницы участников и персональной страницы отдельного участника',
			'архитектура базы данных',
			'настройка mockapi и redux createApi',
		],
		contacts: {
			linkedin: {
				_id: '#linkedin',
				urlPath: 'https://www.linkedin.com/in/grigory-gerasimov-47898516b/',
			},
			telegram: {
				_id: '#telegram',
				urlPath: 'https://t.me/GrigoryGerasimov',
			},
		},
	},
	{
		_category: 'teammates',
		_id: 'mate2',
		firstName: 'Роман',
		lastName: 'Василаки',
		age: '30',
		team: 'Hackathon Team 5',
		position: 'Tech Lead',
		role: 'techlead',
		intro: 'Начинающий ReactJS фронт-энд разработчик',
		imgPath: 'https://media.discordapp.net/attachments/1042002359733198918/1043531733959720981/m3Xsh3pD-cw.jpg',
		hobbies: ['#webtech', '#vid', '#cul', '#cyc'],
		technologies: {
			html: '85',
			css: '75',
			js: '90',
			react: '90',
		},
		tasks: [
			'структура приложения',
			'рефакторинг компонентов страниц',
			'настройка линтера и преттиера, форматирование проекта',
			'разработка лоадера',
			'разработка прогрессбара',
		],
		contacts: {
			telegram: {
				_id: '#telegram',
				urlPath: 'https://t.me/realing29',
			},
			github: {
				_id: '#github',
				urlPath: 'https://github.com/realing29',
			},
		},
	},
	{
		_category: 'teammates',
		_id: 'mate3',
		firstName: 'Станислав',
		lastName: 'Кадыков',
		age: '26',
		team: 'Hackathon Team 5',
		position: 'Front-End Engineer',
		role: 'frontendengineer',
		intro: 'Начинающий ReactJS фронт-энд разработчик',
		imgPath: 'https://media.discordapp.net/attachments/1042002359733198918/1043533509165318275/Screenshot_23.png',
		hobbies: ['#webdes', '#mus', '#vid'],
		technologies: {
			html: '90',
			css: '95',
			css3d: '55',
			js: '80',
			react: '85',
		},
		tasks: [
			'рефакторинг стилей',
			'разработка аутентификации пользователей',
			'разработка навигационной панели',
			'разработка страницы избранное',
			'more to come',
		],
		contacts: {
			discord: {
				_id: '#discord',
				urlPath: '@Tai_SaWFly',
			},
		},
	},
	{
		_category: 'teammates',
		_id: 'mate4',
		firstName: 'Артём',
		lastName: 'Кузнецов',
		age: '32',
		team: 'Hackathon Team 5',
		position: 'Front-End Engineer',
		role: 'frontendengineer',
		intro: 'Начинающий ReactJS фронт-энд разработчик',
		imgPath: 'https://media.discordapp.net/attachments/1042002359733198918/1043534965427679383/U6oyOAbk1to.jpg',
		hobbies: ['#cul', '#cyc', 'hik'],
		technologies: {
			html: '90',
			css: '90',
			js: '80',
			react: '80',
		},
		tasks: [
			'рефакторинг страницы отдельного участника',
			'разработка breadcrumbs',
			'more to come',
		],
		contacts: {
			linkedin: {
				_id: '#linkedin',
				urlPath: 'https://www.linkedin.com/in/artem-kuznetsov-942760243',
			},
			facebook: {
				_id: '#facebook',
				urlPath: 'https://www.facebook.com/artemiusz.kuzniecow?mibextid=ZbWKwL',
			},
		},
	},
]
